### ISSUE TITLE
Frontend: use HTML5 semantic elements

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/emblem#106]
We should move away from using non-semantic HTML elements (e.g. `div`), and towards using more self-explanatory elements [such as these](https://www.w3schools.com/html/html5_semantic_elements.asp).

------
As requested [here](https://github.com/GoogleCloudPlatform/emblem/pull/100#discussion_r668253317).

**Comment by ace-n** [comment]
@pattishin can I reassign this to you? I assume we can fold this into the Lit.dev migration effort.

**Comment by pattishin** [comment]
Closing as this is part of the work in  `experimental/client-app`
