### ISSUE TITLE
productivity: fix code-suggester bugs

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/emblem#143]
## Problem Summary
In #129 and #142, the `code-suggester` setup has resulted in a few fairly major bugs. These bugs cause the affected PRs to become "polluted" with lots of low-value bot comments:

### "Some suggestions could not be made" warnings
These generally apply to large sections of a PR, and can only be resolved by running `black` locally. In some cases, **applying these suggestions results in uncompileable code**.

### CLA check does not recognize GitHub Actions commits
If the linter's suggestions _are_ accepted, the commits happen under an email unknown to the Google CLA checker - which causes _that_ bot to create a bunch of "Unknown committer" comments.

## Recommendations
We can do one of the following:
1. Remove `code-suggester` and make linting a presubmit-blocker only
2. Fix the inaccurate/incorrect suggestions.

Of these, **Option 1** is probably the easiest.

**Comment by pattishin** [comment]
No longer seeing this as an issue for past few months. Closing.
