### ISSUE TITLE
Website: improve EMBLEM_SESSION_BUCKET experience

### ISSUE THREAD

**Issue by kelsk** [GoogleCloudPlatform/emblem#258]
## Problem

The Website README does not contain instructions to set up the required `EMBLEM_SESSION_BUCKET` variable. The Website fails to run without the variable set.
When the `EMBLEM_SESSION_BUCKET` variable is set to a non-existent bucket, the Website runs anyway. Does this mean that the variable is not necessary?

## Steps to Reproduce

1. Run content API locally
2. Set necessary Website env vars detailed in [README.md](https://github.com/GoogleCloudPlatform/emblem/blob/59cda594916e94839b8372eabeedd0cbca7d12f2/website/README.md)
3. Run Website using `flask run`
4. See error below:
    ```
    {"message": "WEBSITE: Could not initialize session module.", "severity": "ERROR"}
    Traceback (most recent call last):
    ...
    Exception: Environment variable EMBLEM_SESSION_BUCKET is required
    ```
5. Set `EMBLEM_SESSION_BUCKET` to "jkljkljkljkljkljkljkljkljkljkljkljkljkljkljkljkl"
6. Validate that this bucket does not exist by running 
    ```
      gsutil list gs://$EMBLEM_SESSION_BUCKET
    ```
7. Run Website using `flask run`
8. See no errors. Interact with Website normally, barring login/authentication

## Expected behavior

- If the `EMBLEM_SESSION_SECRET` variable is required, its value should be validated to ensure the bucket exists and belongs to the account.
- If it's not required, the Website should not fail to run when the var is not supplied.
- The Website README should be updated to include instructions either way.

## Additional context

**User environment:**
- Cloud Shell

**Comment by grayside** [comment]
This issue has been fixed since original creation, authentication is now an optional setup phase that can be done after initial installation.
