### ISSUE TITLE
Demo: Create script to seed database with demo content

### ISSUE THREAD

**Issue by kelsk** [GoogleCloudPlatform/emblem#315]
## Proposal
In order to demonstrate the capabilities of the Emblem application, example data needs to be seeded into the database. 

A script should be added that seeds example data directly into a Firestore database.

## Implementation details
The script will inject data _directly into the database_, bypassing the API. This allows data to be added regardless of whether the API can process the data (i.e., the API is broken, or the data itself is intentionally faulty.)

**Comment by pattishin** [comment]
Base seeding script already in place. Closing.
