### ISSUE TITLE
Docs: Add integration testing for tutorials and READMEs

### ISSUE THREAD

**Issue by kelsk** [GoogleCloudPlatform/emblem#320]
### Issue
When changes are made to Emblem's codebase or architecture, the result can render the docs, tutorials, and diagrams obsolete. In order to avoid broken documentation caused by changes to the project, integration tests should be created to check the new changes against the existing documentation.

### Implementation details for discussion
1: The tests should run as part of the pull request checks on GitHub. 
2: Failing tests should block merging pull requests.
3:

**Comment by pattishin** [comment]
Dup of #189, closing in favor of that issue.
