### ISSUE TITLE
Integrate content seeding into setup.sh

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#346]
We have a content seeding utility at https://github.com/GoogleCloudPlatform/emblem/tree/main/content-api/data.

As described in https://github.com/GoogleCloudPlatform/emblem/tree/main/content-api#seed-database, we can use this to populate an initial approver and initial content in the Firestore database for the API.

We want to run this as part of setup.sh so the out-of-box demo is complete.

If we can default the user email to currently logged in, that would be good but we should tell the user that's what we did and how they can change it.

**Comment by ace-n** [comment]
@grayside and @rogerthatdev have agreed to rework the setup script
