### ISSUE TITLE
Convert Setup Tutorials to single project mode

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/emblem#479]
## Proposal

We want to steer most quick demos to the single project mode, making that the simpler way to get Emblem up and running.

## Problems this will solve

Single project mode is easier to reason about, and easier to make happen in many experimentation environments.

## Actions

* Adjust setup.sh to default to single project mode if production is not defined
* Modify docs/tutorials/setup-quickstart.md to use single project mode
* Modify docs/tutorials/setup-walkthrough.md to use single-project mode
* Document how to set up three-project mode

**Comment by rogerthatdev** [comment]
Checking in: is this still something we want to pursue? It would require a considerable refactor of resources deployed from the terraform app module due to the names of most resources not being unique to their environment (examples: service accounts, cloud run services, triggers)

**Comment by rogerthatdev** [comment]
closing as obsolete
