### ISSUE TITLE
Refactor: move builds out of `ops` to `<COMPONENT>/builds` files

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/emblem#542]
Currently, the various components' Cloud Build files reside in the `/ops` directory. Having several builds (for different components!) in a single directory makes keeping track of the various builds difficult.

We should consider moving these builds alongside their respective components, under a `<COMPONENT_NAME>/builds` path.

--------------------

@grayside @engelke @pattishin what say ye?

**Comment by pattishin** [comment]
Dup. Closing in favor of updated issue: https://github.com/GoogleCloudPlatform/emblem/issues/668
