### ISSUE TITLE
Add descriptions for cloudbuild triggers

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#557]
## Proposal
Add a description for each cloudbuild trigger in the emblem ops project

## Problems this will solve
Descriptions will make it clear what each trigger is designed to accomplish and clarify ambiguity of any names

## Alternatives
N/A

## Additional context
- The triggers are located [here](https://github.com/GoogleCloudPlatform/emblem/blob/main/terraform/modules/ops/build.tf)
- @Breathtender has agreed to pair with @ace-n to take this on. _(Please reach out if you have any questions! 🙂 )_

**Comment by pattishin** [comment]
Merged in https://github.com/GoogleCloudPlatform/emblem/pull/691. Closing.
