### ISSUE TITLE
Decision: document extension model

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/emblem#582]
We should document the "extension" model used by `installation-tests` folder.

(Thanks @rogerthatdev for highlighting this in #414.)

**Comment by ace-n** [comment]
@ace-n to draft; @rorgerthatdev to review. 🙂

**Comment by grayside** [comment]
Note: We are calling this an "extension", plugin has a more specific definition.

**Comment by pattishin** [comment]
Becoming obsolete, closing out at this time.
