### ISSUE TITLE
doc: improve README to provide context on tutorial/walkthrough

### ISSUE THREAD

**Issue by iennae** [GoogleCloudPlatform/emblem#590]
feedback from @glasnt 

Looking at the readme, I see I can either read the quickstart or launch the interactive walkthrough. 

Quickstart: [github.com/GoogleCloudPlatform/emblem/blob/main/docs/tutorials/setup-quickstart.md](https://github.com/GoogleCloudPlatform/emblem/blob/main/docs/tutorials/setup-quickstart.md)
Has a button to launch Cloud Shell

Walkthrough: [github.com/GoogleCloudPlatform/emblem/blob/main/docs/tutorials/setup-walkthrough.md](https://github.com/GoogleCloudPlatform/emblem/blob/main/docs/tutorials/setup-walkthrough.md)
IS the walkthrough. 
Has the <walkthrough-..>tags.

These files looks like they're duplicates of each other; Is this intentional?

**Comment by rogerthatdev** [comment]
Resolved by #679 - root README will be the centralized location of 'Getting Started'
