### ISSUE TITLE
Document project boundaries and components

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#600]
from @glasnt feedback
Where are the project boundaries?

We should provide clear documentation in the primary README of each individual Google Cloud projects used in an Emblem deployment and their components (application, testing and delivery pipeline, etc). 

Related:

- [x] #659

**Comment by pattishin** [comment]
Closing, resolved by https://github.com/GoogleCloudPlatform/emblem/pull/694
