### ISSUE TITLE
Re-applying Terraform destroys google_app_engine_application.main

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#603]
from @glasnt feedback

## Problem
During setup, rerunning `setup.sh `and the terraform it executes destroys the `google_app_engine_application.main `resource without clear indication why. 

## Steps to Reproduce

1. Run `setup.sh` until after prod or stage is setup
2. Re-run `setup.sh`
3. Observe output of `terraform apply`

## Expected behavior
This is expected behavior but it is reasonable to expect that Terraform run twice in a row should not destroy previously created resources. Otherwise, we should indicate in the comments or documentation that this is expected behavior.  

## Additional context

Terraform is not able to create the `google_app_engine_application` resource if the project already has an AppEngine app in it. It also is unable to delete the resource from a project when using `terraform destroy.` In order to support running `terraform apply` on a project that may already have an appengine application and running `terraform apply` after a `terraform destroy`, the tf checks to see if an appengine service account exists: and if it does it sets the AppEngine resource `count` to 0. This causes it to destroy the resource on re-apply. 

This does not impact the functionality of the Emblem deployment.

**Screenshots**
```
Plan: 0 to add, 0 to change, 1 to destroy.
module.emblem_prod.google_app_engine_application.main[0]: Destroying... [id=katiecloudda-emblem-prod]
module.emblem_prod.google_app_engine_application.main[0]: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

**Comment by rogerthatdev** [comment]
Proposal - add a check at the start of setup.sh to check if Terraform steps were already previously run successfully.

**Comment by ace-n** [comment]
I wasn't able to repro this.

@glasnt should we close this, or would you want to pair with me on it?

> I'm inclined to close this, given that it doesn't seem to break anything.

**Comment by glasnt** [comment]
In my case I had a half-processed deployment, so I'm unsure if this only came up in that situation.

I think it should be as simple as adding a `prevent_destroy` or similar (like for APIs and other fundamental non-ephemeral infra)

**Comment by ace-n** [comment]
@grayside would that brick the `apply-destroy-apply` flow we discussed in #224? If so, does that matter?

(Perhaps #224 is no longer relevant, given our migration to remote state.)

**Comment by rogerthatdev** [comment]
Note on this: it's only reproducible on a brand new project when re-running setup.sh a second time.  If reusing a project that already has AppEngine, the terraform will never create the resource in the first place so it'll never have to destroy it.  Adding `prevent_destroy` will complicate the clean up of resources.


Given that this would only typically happen for half-processed deployments, and it actually doesn't stop the setup from continuing, we can probably safely close this issue or deprioritize.
