### ISSUE TITLE
feat: debug link from frontend to cloud console

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#605]
Difficult to go from the donation confirmation in the app to the interesting correlated log results. Would be great if the trace were sent back and a "debug" link were part of the donation confirm page to deep link to a page like https://console.cloud.google.com/logs/query;query=trace%3D%22projects%2Femblem-ci-stage%2Ftraces%2Fea331d42bbea0cf89aab98c4984a8445%22?project=emblem-ci-stage

**Comment by pattishin** [comment]
PR: https://github.com/GoogleCloudPlatform/emblem/pull/620
