### ISSUE TITLE
Verify seeding step w/ python is no longer erroring out

### ISSUE THREAD

**Issue by pattishin** [GoogleCloudPlatform/emblem#657]
Ref: [Demo/bug bash session](https://docs.google.com/document/d/19nq5cM26rM17ZD-LP999Y9Jndwp5bLo-bFa-J0kl3K4/edit#bookmark=id.rstdqp31q1p2)

Executed `setup.sh` in a new GCP project within emblem repo.
This halted entire setup script and temp resolved by globally installing w/ `pip3 install google-cloud-firestore`
Had to re-execute `setup.sh` to pick up where we left off.

Open issue by Charlie for Cloud Shell team. (https://buganizer.corp.google.com/issues/245966557)

**Comment by rogerthatdev** [comment]
I will make sure seeding python script works in a default Cloud Shell environment as a baseline

**Comment by rogerthatdev** [comment]
Based on discussion, we will replace the python step with a cloud build job that will seed firebase with test data.
