### ISSUE TITLE
Clarify in docs about "ops" project as only github touchpoint

### ISSUE THREAD

**Issue by pattishin** [GoogleCloudPlatform/emblem#659]
Ref: [Demo/Bug bash sessions](https://docs.google.com/document/d/19nq5cM26rM17ZD-LP999Y9Jndwp5bLo-bFa-J0kl3K4/edit#bookmark=id.2owrui99qfqv)

Add in more color and explanation around why the ops project contains all the Cloud Build trigger, OAuth, etc.

**Comment by rogerthatdev** [comment]
closing in favor of #655
