### ISSUE TITLE
streamline `setup.sh`

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#677]
## Proposal
Set default behavior of `setup.sh` to deploy a minimal deployment of Emblem by always [setting up CI/CD](https://github.com/GoogleCloudPlatform/emblem/blob/b86e368709cb02d5c393e150c5b804c0e536a412/setup.sh#L246) and [skipping authentication setup](https://github.com/GoogleCloudPlatform/emblem/blob/b86e368709cb02d5c393e150c5b804c0e536a412/setup.sh#L225) by default.  Also move any remaining required user input to the beginning of the script.

## Problems this will solve

- CI/CD is a primary thing that Emblem is meant to demonstrate - this can safely be made a default behavior of a common setup.
- The auth step requires several steps between console and CLI and takes several minutes. Many demos may not require authentication. Those that do will be able to specify a special flag for `setup.sh` or documented step for adding auth to a deployed instance of Emblem.

## Additional context
- Initial Emblem content will not require functioning authentication

**Comment by pattishin** [comment]
Closing after @rogerthatdev's PR https://github.com/GoogleCloudPlatform/emblem/pull/700
