### ISSUE TITLE
Cloud Shell: `cannot assign requested address` when running setup terraform

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#712]
## Problem

When running `setup.sh` in Cloud Shell, an error will sometimes interrupt the Terraform when deploying some resources:
```
[2607:f8b0:4001:c0c::5f]:443: connect: cannot assign requested address
```

This is an issue having to do with the Terraform provider attempting to resolve Google API URLs using IPv6 AAAA records instead of IPv4 A records. 

This is the same issue being [tracked in the Google provider repo](https://github.com/hashicorp/terraform-provider-google/issues/6782#issuecomment-829642571).  

[Workaround on StackOverflow](https://stackoverflow.com/questions/62106154/frequent-error-when-deploying-helm-to-gke-with-terraform)

## Steps to Reproduce

1. Run `setup.sh` from Cloud Shell
2. Error may or may not occur

## Expected behavior

No error when using Cloud Shell.

## Additional context

**Error:**
```
│ Error: Error when reading or editing Service Account "projects/wildsun-emblem-stage/serviceAccounts/website-manager@wildsun-emblem-stage.iam.gserviceaccount.com": Get "https://iam.googleapis.com/v1/projects/wildsun-emblem-stage/serviceAccounts/website-manager@wildsun-emblem-stage.iam.gserviceaccount.com?alt=json&prettyPrint=false": dial tcp [2607:f8b0:4001:c0c::5f]:443: connect: cannot assign requested address
│
│   with module.emblem_staging.google_service_account.website_manager,
│   on ../../modules/emblem-app/iam.tf line 8, in resource "google_service_account" "website_manager":
│    8: resource "google_service_account" "website_manager" {
│
╵
╷
│ Error: Error when reading or editing Service Account "projects/-/serviceAccounts/wildsun-emblem-stage@appspot.gserviceaccount.com": Get "https://iam.googleapis.com/v1/projects/-/serviceAccounts/wildsun-emblem-stage@appspot.gserviceaccount.com?alt=json&prettyPrint=false": dial tcp [2607:f8b0:4001:c0c::5f]:443: connect: cannot assign requested address
│
│   with module.emblem_staging.data.google_app_engine_default_service_account.default,
│   on ../../modules/emblem-app/main.tf line 14, in data "google_app_engine_default_service_account" "default":
│   14: data "google_app_engine_default_service_account" "default" {
│
╵
Exited [1] at line 275 setup.sh:
   272  if [[ -z "$SKIP_TRIGGERS" ]]; then
   273      echo
   274
>>> 275     sh ./scripts/configure_delivery.sh
   276
   277  fi # skip triggers
   278
```
**User environment:**
 - Cloud Shell `uname -srv`: `Linux 5.10.147+ #1 SMP Fri Nov 4 08:53:26 UTC 2022`

**Comment by rogerthatdev** [comment]
We could possible avert this error completely if we execute all terraform as Cloud Build jobs.

**Comment by ace-n** [comment]
If we wanted end-users to see the Terraform plan pre-applying, moving `tf apply` to Cloud Build might be problematic.

<details>
<summary>Here is a (horrifying 😱 && not encouraged 👎 ) workaround for that </summary>
We _could_ use a shell script with `dig` and `sed` to [update `/etc/hosts` on Cloud Shell](https://stackoverflow.com/questions/62106154/frequent-error-when-deploying-helm-to-gke-with-terraform#:~:text=export%20APIS%3D%22googleapis.com%20www.googleapis.com%20storage.googleapis.com%20iam.googleapis.com%20container.googleapis.com%20cloudresourcemanager.googleapis.com%22%0Afor%20i%20in%20%24APIS%0Ado%0A%20%20echo%20%22199.36.153.10%20%24i%22%20%3E%3E%20/etc/hosts%0Adone).
</details>

**Comment by rogerthatdev** [comment]
At the moment, users can't see the terraform plan output anyway in the setup script. On the contrary,  running it in a build job will preserve the output so they can read through it after apply.

**Comment by rogerthatdev** [comment]
See PR #724 (draft) for experimental solution
