### ISSUE TITLE
Task: create example API <-> web site connection

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/emblem#75]
### Plan
As requested in today's meeting by @grayside, @engelke and myself should collaborate to create an example connection between the API and the website.

We're aiming to have an example (hard-coded) response for at least one API resource (likely `Campaigns`) available by **Wednesday evening**. We can then integrate that response into the frontend.

### Observations + questions
- The `content-api` folder seems to demonstrate the API itself converting from HTTP requests to Python objects. @engelke is this something we can rely on? (It makes my job significantly easier vs. having the website parse HTTP responses, but I don't want to rely on this without asking.)
- The website currently uses [this file](https://github.com/GoogleCloudPlatform/emblem/blob/main/website/app.py#L27-L60) to store sample data. (This is being moved to `website/sample_data.py` in [this PR](#74)). I assume the datatypes we use in this [initial] demo will be either the same as those, or fairly similar?

**Comment by engelke** [comment]
This was completed some time ago.
