### ISSUE TITLE
Cloud Build SA needs Service Account Token Creator role

### ISSUE THREAD

**Issue by engelke** [GoogleCloudPlatform/emblem#755]
If the Cloud Build Service Account (or any account that tries to run the Content API unit tests) does not have Service Account Token Creator role, it will not be able to fetch an id token for the test user service account.

Without that id token, none of the tests can pass.

As of the time of this issue, that role has been manually assigned, but needs to be added to the automated setup of new projects.

**Comment by grayside** [comment]
This issue does not affect our maintenance projects, but will affect anyone that sets up Emblem and seeks to explore the full test lifecycle.

**Comment by grayside** [comment]
It looks like this was fixed by #665, merged in September 2022.
