### ISSUE TITLE
break up `web-e2e.cloudbuild.yaml` into multiple steps

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#756]
## Proposal
`web-e2e.cloudbuild.yaml` can be refactored into multiple cloud build steps.

## Problems this will solve
Current e2e test does the following in one single step via bash entrypoint:
- copies files from `client-libs`
- installs python requirements via pip
- runs flask python module
- traverses container filesystem
- installs node dependencies via npm
- runs `npm test`

This makes for a difficult time troubleshooting and reviewing logs.

**Comment by ace-n** [comment]
We'll have to pass data between steps, which can be done using [workspaces](https://cloud.google.com/build/docs/configuring-builds/pass-data-between-steps#passing_data_using_workspaces).
