### ISSUE TITLE
e2e-runner build in set up fails

### ISSUE THREAD

**Issue by rogerthatdev** [GoogleCloudPlatform/emblem#763]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: This repository is dedicated to a sample application that uses multiple Google Cloud products. We will only be able to address issues related to this application, not to underlying issues in a client library or one of the products. Please visit the [Support page](https://cloud.google.com/support) to reach the most relevant engineers.

## Problem

During setup, the build for e2e-runner fails due to referencing a non-existant AR repo

## Steps to Reproduce

1. Run setup
2. See build logs for job that builds e2e runner

## Expected behavior
e2e runner should build during setup.  Solution is to make sure the [e2e runner is built](https://github.com/GoogleCloudPlatform/emblem/blob/9d3524a1f50becb92a6710001f9a22593a54c137/setup.sh#L105) only after the e2e testing module is deployed.

## Additional context
Error:
```
ERROR: error pushing image "us-central1-docker.pkg.dev/emblem-ops-8499/e2e-testing/runner:latest": generic::unknown: retry budget exhausted (10 attempts): step exited with non-zero status: 1
ERROR
ERROR: failed to push because we ran out of retries.
ERROR: push attempt 10 detected failure, retrying: step exited with non-zero status: 1
name unknown: Repository "e2e-testing" not found
```

**Comment by ace-n** [comment]
I'd argue we should move this build into `scripts/configure_delivery.sh`, as it seems like most CI/CD resources (including E2E test materials) are handled there.

@rogerthatdev any objections?

**Comment by rogerthatdev** [comment]
> 
yeah that sounds right
