### ISSUE TITLE
`ops/e2e-runner-build.cloudbuild.yaml` does not exist

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/emblem#898]
When running `./setup.sh` the process fails, since `ops/e2e-runner-build.cloudbuild.yaml` does not exist when called in 
[`configure_delivery.sh`](https://github.com/GoogleCloudPlatform/emblem/blob/main/scripts/configure_delivery.sh#LL97C14-L97C50).

**Comment by rogerthatdev** [comment]
This was resolved by #919
