### ISSUE TITLE
delivery: Manage configuration change with Terraform

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/emblem#97]
## Background

Currently the terraform files are only geared at initial setup.  They should be updated to store a remote state so teams can iterate on them and update the project together.  

## Proposal

* Use [Remote State](https://www.terraform.io/docs/language/state/remote.html) to source state from Cloud Storage.
* Use a single Cloud Storage bucket in the the Ops project, but separate environments by top-level "folders".
* Parameterize the location of this bucket so it can be injected via `terraform init` in our setup process.

## Future

* Import CI project into terraform state so we can manage via terraform
* Terraform changes should have plans generated for review, for best results comment these on the PR. Clean slate and diff from current stage state would both provide useful insight.
* Ship changes to Stage on merged PRs. Should this require approval?
* Ship changes to Prod when Stage infra is updated successfully. Should this require approval?
* Remove/simplify terraform cleanup script in favor of terraform destroy covering all steps

**Comment by grayside** [comment]
For lack of this issue, we have reached the stage of needing to manually synchronize our CI projects with terraform config changes in the repo. Raising priority to P1.
